zvision_lidar_cloud_node:
    ros__parameters:
        angle_path: ""
        model: MLXS
        downsample_type: None
        line_sample: 2
        voxel_leaf_size: 0.2f
        use_lidar_time: false
        x_tra: 0.0
        y_tra: 0.0
        z_tra: 0.0
        x_rot: 0.0
        y_rot: 0.0
        z_rot: 0.0
